services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bin
    ports:
      - "8000:8000"
    volumes:
      - pastes:/app/pastes
    user: 1000:1000

volumes:
  pastes:
